site_name: MCUT

markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - markdown.extensions.footnotes
  - markdown.extensions.smarty
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.emoji

extra:
  search:
    tokenizer: '[\s\-\.::]+'

theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'red'
  font:
    text: 'Merriweather'
    code: 'Inconsolata'
  icon: 
    logo: material/home

extra_css:
  - extras.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

google_analytics: ['UA-58346315-3', 'auto']

repo_name: 'cutdigital/mcut-site'
repo_url: 'https://github.com/cutdigital/mcut-site.git'

# https://github.com/pieterdavid/mkdocs-doxygen-plugin
plugins:
  - doxygen:
      tryclone: yes
      packages:
        - doxygen:
            url: . # location of Doxyfile
        - doxyfwk:
            url    : https://github.com/cutdigital/mcut-headers.git
            config : Doxyfile
            workdir: . ## could be left out in this case

nav:
  - Home: 'index.md'
  - Setup : 'building.md'
  - Tutorials : 
    - 'Using MCUT' : 'tutorials/using.md'
    - 'Hello triangle' : 'tutorials/hello_triangle.md'
    - 'Mesh setup' : 'tutorials/load_mesh.md'
    - 'Debugging' : 'tutorials/debugging.md'
  - Docs : 'site/doxygen/index.html'
  - Caveats: 'caveats.md'
  #- License: 'license.md'
  #- Acknowledge : 'acknowledgement.md'

